[tool.poetry]
name = "solanace"
version = "0.1.0"
description = ""
authors = ["Elia Hilse"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
